### ISSUE TITLE
Docker location missing in the list 

### ISSUE THREAD

**Issue by nazymko** [localstack/localstack-java-utils#38]
Currently, the library looking for a docker executable in few places, but the latest docker installation has it in docker\resources\docker.exe 
`C:\Program Files\Docker\Docker\resources\docker.exe`
but it looking for a file in the 'bin' folder 
C:\Program Files\Docker\Docker\resources\**bin**\docker.exe

List of possible locations have to be updated 

`cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
	at cloud.localstack.Localstack.startup(Localstack.java:90)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:41)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.IllegalStateException: Cannot find docker executable.
	at cloud.localstack.docker.DockerExe.lambda$getDockerExeLocation$1(DockerExe.java:43)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at cloud.localstack.docker.DockerExe.getDockerExeLocation(DockerExe.java:43)
	at cloud.localstack.docker.DockerExe.<init>(DockerExe.java:35)
	at cloud.localstack.docker.command.Command.<init>(Command.java:11)`

**Comment by whummer** [comment]
Thanks for reporting @nazymko . Do you think you could create a small pull request with this change? That would be much appreciated - many thanks for your help.

**Comment by nazymko** [comment]
This location was added recently to 0.2.7 (I was using 0.2.5)
