### ISSUE TITLE
Upgrade to com.amazonaws:aws-lambda-java-events:3.7.0 breaks compile

### ISSUE THREAD

**Issue by akutschera** [localstack/localstack-java-utils#48]
I recently tried to run a Java Lambda that consumes a DynamodbEvent on localstack. My lambda was never called because of

    2021-03-25T17:46:47:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function 
    arn:aws:lambda:us-east-1:000000000000:function:localstack-issue: Lambda process returned error status code: 1. Result: . Output:
    Exception in thread "main" java.lang.NoSuchMethodError: 'void com.amazonaws.services.lambda.runtime.events.DynamodbEvent$DynamodbStreamRecord.setEventName(com.amazonaws.services.dynamodbv2.model.OperationType)'
	     at cloud.localstack.lambda.DDBEventParser.parse(DDBEventParser.java:24)
	     at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:84)

This was probably because my lambda was compiling against com.amazonaws:aws-lambda-java-events:3.7.0 and this project is running with version 2.2.7
This could also be the cause of https://github.com/localstack/localstack/issues/1960
Is there way to make localstack work with lambdas that use aws-lambda-java-events:3.7.0 ?

**Comment by productivityindustries** [comment]
I'd also like to know if there's any update/workaround on this issue. Thanks

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version of LocalStack? We would appreciate your feedback!
